version: "2"
services:
  redis-1:
    container_name: session-redis-0
    build: 
      context: ./1
      dockerfile: Dockerfile
    ports: 
      - "7000:7000"
      - "17000:17000"
    networks: 
      - session-redis-net
    entrypoint: [redis-server, /usr/local/etc/redis/redis.conf, --port , "7000", --cluster-announce-ip, "${ip}"]
  redis-2:
    container_name: session-redis-1
    build: 
      context: ./1
      dockerfile: Dockerfile
    ports: 
      - "7001:7001"
      - "17001:17001"
    networks: 
      - session-redis-net
    entrypoint: [redis-server, /usr/local/etc/redis/redis.conf, --port , "7001", --cluster-announce-ip, "${ip}"]
  redis-3:
    container_name: session-redis-2
    build: 
      context: ./1
      dockerfile: Dockerfile
    ports: 
      - "7002:7002"
      - "17002:17002"
    networks: 
      - session-redis-net
    entrypoint: [redis-server, /usr/local/etc/redis/redis.conf, --port , "7002", --cluster-announce-ip, "${ip}"]
  redis-4:
    container_name: session-redis-3
    build: 
      context: ./1
      dockerfile: Dockerfile
    ports:
      - "7003:7003"
      - "17003:17003"
    networks: 
      - session-redis-net
    entrypoint: [redis-server, /usr/local/etc/redis/redis.conf, --port , "7003", --cluster-announce-ip, "${ip}"]
  redis-5:
    container_name: session-redis-4
    build: 
      context: ./1
      dockerfile: Dockerfile
    ports:
      - "7004:7004"
      - "17004:17004"
    networks: 
      - session-redis-net
    entrypoint: [redis-server, /usr/local/etc/redis/redis.conf, --port , "7004", --cluster-announce-ip, "${ip}"]
  redis-6:
    container_name: session-redis-5
    build: 
      context: ./1
      dockerfile: Dockerfile
    ports:
      - "7005:7005"
      - "17005:17005"
    networks: 
      - session-redis-net
    entrypoint: [redis-server, /usr/local/etc/redis/redis.conf, --port , "7005", --cluster-announce-ip, "${ip}"]

  redis-creater:
    image: redis:5.0.7
    entrypoint: [/bin/sh,-c,'echo "yes" | redis-cli --cluster create ${ip}:7000 ${ip}:7001 ${ip}:7002 ${ip}:7003 ${ip}:7004 ${ip}:7005 --cluster-replicas 1']
    networks: 
      - session-redis-net
    depends_on: 
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
networks:
  session-redis-net:
    driver: bridge    